#!/bin/sh
set -eu

mc alias set local http://minio:9000 "${MINIO_ROOT_USER}" "${MINIO_ROOT_PASSWORD}"
mc mb --ignore-existing "local/${MINIO_BUCKET}"

# The real files are generated by build-msd-lung-glb.py and mounted at /seed.
seed_layer() {
  layer="$1"
  source="$2"
  for variant in low medium high; do
    source_file="/seed/${source}.${variant}.glb"
    target="local/${MINIO_BUCKET}/demo/demo-lung/${layer}/${variant}.glb"
    if [ ! -f "$source_file" ]; then
      echo "Missing real demo mesh: $source_file" >&2
      exit 1
    fi
    mc cp "$source_file" "$target"
  done
}

seed_layer rs1 lung-upper-lobe-right
seed_layer rs2 lung-middle-lobe-right
seed_layer rs3 lung-lower-lobe-right
seed_layer rs4 lung-upper-lobe-left
seed_layer rs5 lung-lower-lobe-left
